package com.example.factorygeneral.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.factorygeneral.greendao.bean.MenusListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MENUS_LIST_BEAN".
*/
public class MenusListBeanDao extends AbstractDao<MenusListBean, Long> {

    public static final String TABLENAME = "MENUS_LIST_BEAN";

    /**
     * Properties of entity MenusListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UId = new Property(0, Long.class, "uId", true, "_id");
        public final static Property IsCheck = new Property(1, boolean.class, "isCheck", false, "IS_CHECK");
        public final static Property Id = new Property(2, String.class, "id", false, "ID");
        public final static Property KeyId = new Property(3, String.class, "keyId", false, "KEY_ID");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property UserName = new Property(5, String.class, "userName", false, "USER_NAME");
        public final static Property Uuid = new Property(6, String.class, "uuid", false, "UUID");
    }


    public MenusListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MenusListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MENUS_LIST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uId
                "\"IS_CHECK\" INTEGER NOT NULL ," + // 1: isCheck
                "\"ID\" TEXT," + // 2: id
                "\"KEY_ID\" TEXT," + // 3: keyId
                "\"NAME\" TEXT," + // 4: name
                "\"USER_NAME\" TEXT," + // 5: userName
                "\"UUID\" TEXT);"); // 6: uuid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MENUS_LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MenusListBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
        stmt.bindLong(2, entity.getIsCheck() ? 1L: 0L);
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(4, keyId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(6, userName);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(7, uuid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MenusListBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
        stmt.bindLong(2, entity.getIsCheck() ? 1L: 0L);
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(4, keyId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(6, userName);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(7, uuid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MenusListBean readEntity(Cursor cursor, int offset) {
        MenusListBean entity = new MenusListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uId
            cursor.getShort(offset + 1) != 0, // isCheck
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // keyId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // userName
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // uuid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MenusListBean entity, int offset) {
        entity.setUId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIsCheck(cursor.getShort(offset + 1) != 0);
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setKeyId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUuid(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MenusListBean entity, long rowId) {
        entity.setUId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MenusListBean entity) {
        if(entity != null) {
            return entity.getUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MenusListBean entity) {
        return entity.getUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
