package com.example.factorygeneral.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.factorygeneral.greendao.bean.ModuleListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MODULE_LIST_BEAN".
*/
public class ModuleListBeanDao extends AbstractDao<ModuleListBean, Long> {

    public static final String TABLENAME = "MODULE_LIST_BEAN";

    /**
     * Properties of entity ModuleListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UId = new Property(0, Long.class, "uId", true, "_id");
        public final static Property Uuid = new Property(1, String.class, "uuid", false, "UUID");
        public final static Property Id = new Property(2, String.class, "id", false, "ID");
        public final static Property KeyId = new Property(3, String.class, "keyId", false, "KEY_ID");
        public final static Property KeyUuid = new Property(4, String.class, "keyUuid", false, "KEY_UUID");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property UserName = new Property(6, String.class, "userName", false, "USER_NAME");
    }


    public ModuleListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ModuleListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MODULE_LIST_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uId
                "\"UUID\" TEXT," + // 1: uuid
                "\"ID\" TEXT," + // 2: id
                "\"KEY_ID\" TEXT," + // 3: keyId
                "\"KEY_UUID\" TEXT," + // 4: keyUuid
                "\"NAME\" TEXT," + // 5: name
                "\"USER_NAME\" TEXT);"); // 6: userName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MODULE_LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ModuleListBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(4, keyId);
        }
 
        String keyUuid = entity.getKeyUuid();
        if (keyUuid != null) {
            stmt.bindString(5, keyUuid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(7, userName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ModuleListBean entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(2, uuid);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(4, keyId);
        }
 
        String keyUuid = entity.getKeyUuid();
        if (keyUuid != null) {
            stmt.bindString(5, keyUuid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(7, userName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ModuleListBean readEntity(Cursor cursor, int offset) {
        ModuleListBean entity = new ModuleListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uuid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // keyId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // keyUuid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // userName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ModuleListBean entity, int offset) {
        entity.setUId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setKeyId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setKeyUuid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUserName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ModuleListBean entity, long rowId) {
        entity.setUId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ModuleListBean entity) {
        if(entity != null) {
            return entity.getUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ModuleListBean entity) {
        return entity.getUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
